name: OpenVote
version: ${project.version}-git-${git.commit.id.abbrev}
main: eu.okaeri.minecraft.openvote.bukkit.OpenVoteBukkitPlugin
description: 'OK! OpenVote Minecraft (Bukkit)'
author: 'Dawid Sawicki <dawid@okaeri.eu>'
api-version: 1.13
