################################################################
#                                                              #
#    OK! No.Proxy Minecraft                                    #
#                                                              #
#    Nie wiesz jak skonfigurować? Zerknij do dokumentacji!     #
#    https://wiki.okaeri.eu/pl/uslugi/noproxy/minecraft        #
#                                                              #
#    Trouble configuring? Check out the documentation!         #
#    https://wiki.okaeri.eu/en/services/noproxy/minecraft      #
#                                                              #
################################################################


# Klucz prywatny API
# API secret
token: ""

# Wiadomosci
# Messages
message-prefix: "&f&lNo.Proxy&7: "
message-player-info: |-
  {PREFIX}&cKorzystanie z serwerow VPN lub proxy jest zabronione na tym serwerze.
  &cJesli uwazasz to za blad, skontaktuj sie z administracja.
  &f
  &cPomoc: &ehttps://example.com/forum

# Biala lista (wpisane nicki lub ip nie beda blokowane)
# Whitelist (nicknames or ips)
white-list:
  - 127.0.0.1

# Nie edytuj tej wartosci
# Do not edit
version: 2
