name: NoProxy
version: ${project.version}-git-${git.commit.id.abbrev}
main: eu.okaeri.minecraft.noproxy.bukkit.NoProxyBukkitPlugin
description: 'OK! No.Proxy Minecraft (Bukkit)'
author: 'Dawid Sawicki <dawid@okaeri.eu>'
api-version: 1.13
